application:
  http:
    admin:
      contextPath: /short-link
      host: 127.0.0.1
      port: 8088
      mode: debug
    app:
      contextPath: /
      host: 127.0.0.1
      port: 8081
      mode: debug
    metrics:
      contextPath: /
      host: 127.0.0.1
      port: 2112
      mode: debug
  logger:
    level: debug
    stdType: file
    filePath: /Users/ethanleo/GolandProjects/short-link/log/app.log
database:
  mysql:
    default:
      host: "127.0.0.1"
      port: 3306
      dbname: "short_link"
      user: "root"
      password: "wanyuqin0531"
  redis:
    default:
      host: "127.0.0.1"
      port: 6379
      db: 0
      password: ""
hotkey:
  interval: 3  # 时间间隔
  threshold: 10 # 阈值