definitions:
  controller.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
      timeStamp:
        type: integer
    type: object
  request.AddLinkReq:
    properties:
      expiredAt:
        type: integer
      originalUrl:
        type: string
      userId:
        type: integer
    type: object
  request.LoginReq:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  request.RegisterReq:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
info:
  contact: {}
paths:
  /link/add:
    post:
      consumes:
      - application/json
      description: 添加链接
      parameters:
      - description: 注册请求参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/request.AddLinkReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Response'
      summary: 添加链接
      tags:
      - 链接
  /users/login:
    post:
      consumes:
      - application/json
      description: 用户登陆
      parameters:
      - description: 注册请求参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/request.LoginReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Response'
      summary: 用户登陆
      tags:
      - 用户
  /users/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: 注册请求参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/request.RegisterReq'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Response'
      summary: 用户注册
      tags:
      - 用户
swagger: "2.0"
